spring:
  application:
    name: cassandra-app
  cassandra:
    local-datacenter: datacenter1
    contact-points: localhost
    port: 9042
    keyspace-name: mykeyspace
    schema-action: create_if_not_exists

server:
  port: 8080
